services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # S3 API 端口
      - "9001:9001" # 控制台端口
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
